'use strict';

/**
 * Draws the application icon and writes it as build/icon.png.
 *
 * Generated by code rather than checked in as a binary, so the icon can be
 * recoloured by editing two constants instead of opening an image editor.
 * electron-builder converts this PNG into the .ico Windows needs.
 *
 * Run: node scripts/make-icon.js
 */

const fs = require('node:fs');
const path = require('node:path');
const zlib = require('node:zlib');

const SIZE = 256;
const BACKGROUND = [232, 116, 156]; // --accent, the pink from the app
const MARK = [255, 255, 255];
const CORNER_RADIUS = 56;

/** Three bars of different heights: a board with its columns. */
const COLUMNS = [
  { x: 62, y: 76, width: 36, height: 118 },
  { x: 110, y: 76, width: 36, height: 76 },
  { x: 158, y: 76, width: 36, height: 100 },
];

function isInsideRoundedSquare(x, y) {
  const r = CORNER_RADIUS;
  const near = (v, edge) => (v < edge ? edge - v : 0);

  // Distance past the straight edges, in each direction.
  const dx = Math.max(near(x, r), x > SIZE - r ? x - (SIZE - r) : 0);
  const dy = Math.max(near(y, r), y > SIZE - r ? y - (SIZE - r) : 0);

  return dx * dx + dy * dy <= r * r;
}

function isInsideColumn(x, y) {
  return COLUMNS.some(
    (c) => x >= c.x && x < c.x + c.width && y >= c.y && y < c.y + c.height,
  );
}

function buildPixels() {
  // One filter byte per row, then RGBA for every pixel.
  const raw = Buffer.alloc(SIZE * (1 + SIZE * 4));
  let offset = 0;

  for (let y = 0; y < SIZE; y++) {
    raw[offset++] = 0; // filter type "none"

    for (let x = 0; x < SIZE; x++) {
      const inside = isInsideRoundedSquare(x + 0.5, y + 0.5);
      const colour = isInsideColumn(x, y) ? MARK : BACKGROUND;

      raw[offset++] = colour[0];
      raw[offset++] = colour[1];
      raw[offset++] = colour[2];
      raw[offset++] = inside ? 255 : 0; // transparent outside the rounded square
    }
  }

  return raw;
}

function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);

  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);

  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body) >>> 0);

  return Buffer.concat([length, body, crc]);
}

const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) {
      c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    }
    table[n] = c;
  }
  return table;
})();

function crc32(buffer) {
  let c = -1;
  for (const byte of buffer) {
    c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  }
  return c ^ -1;
}

function buildPng() {
  const signature = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(SIZE, 0);
  ihdr.writeUInt32BE(SIZE, 4);
  ihdr[8] = 8; // bits per channel
  ihdr[9] = 6; // colour type: RGBA
  ihdr[10] = 0; // deflate
  ihdr[11] = 0; // default filtering
  ihdr[12] = 0; // no interlacing

  return Buffer.concat([
    signature,
    chunk('IHDR', ihdr),
    chunk('IDAT', zlib.deflateSync(buildPixels(), { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

const outputDir = path.join(__dirname, '..', 'build');
fs.mkdirSync(outputDir, { recursive: true });

const outputFile = path.join(outputDir, 'icon.png');
fs.writeFileSync(outputFile, buildPng());

console.log(`Icon written: ${outputFile} (${SIZE}x${SIZE})`);
